// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_4e-DEJTIewwDy7xen91TpbofEL34cs',
    appId: '1:352122376511:web:1fde2a337384bf7504438a',
    messagingSenderId: '352122376511',
    projectId: 'imageandvideoupload-47873',
    authDomain: 'imageandvideoupload-47873.firebaseapp.com',
    storageBucket: 'imageandvideoupload-47873.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9YDvnrOGKh0XOlWD-v4_b7EXTO6KhgGk',
    appId: '1:352122376511:android:5235c24a4c669a1804438a',
    messagingSenderId: '352122376511',
    projectId: 'imageandvideoupload-47873',
    storageBucket: 'imageandvideoupload-47873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjJwcFWHh1aeDBXapl1QGM-aBszljtd8',
    appId: '1:352122376511:ios:c36dbee65aaf20c404438a',
    messagingSenderId: '352122376511',
    projectId: 'imageandvideoupload-47873',
    storageBucket: 'imageandvideoupload-47873.appspot.com',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwjJwcFWHh1aeDBXapl1QGM-aBszljtd8',
    appId: '1:352122376511:ios:892253b5d9032b2904438a',
    messagingSenderId: '352122376511',
    projectId: 'imageandvideoupload-47873',
    storageBucket: 'imageandvideoupload-47873.appspot.com',
    iosBundleId: 'com.example.assignment1.RunnerTests',
  );
}
